image: maven:3.6.3-jdk-8

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: test
  allow_failure: true
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
    
  script:
    # Run your tests
    - echo "Executing BDD scenarios with maven"
    - mvn clean verify -Dcucumber.options=src/test/resources/features
  
  after_script:
    - rm -rf /var/lib/apt/lists/*
    - apt-get update
    - apt-cache gencaches
    - apt-get install -y zip unzip
    - zip -r serenity_report.zip ./target/serenity
    
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ./serenity_report.zip 
    
